version: '3.8'

services:
  # Development service
  shofi-grocery-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: shofi-grocery-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    command: npm run dev
    restart: unless-stopped
    networks:
      - shofi-network
    profiles:
      - dev

  # Production service
  shofi-grocery-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: shofi-grocery-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: unless-stopped
    networks:
      - shofi-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - prod

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: shofi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - shofi-grocery-prod
    restart: unless-stopped
    networks:
      - shofi-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    profiles:
      - prod

networks:
  shofi-network:
    driver: bridge 